version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: "terraform"
    directory: "/infrastructure"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    groups:
      all:
        patterns: ["*"]
